### ISSUE TITLE
Prod setup for Docker Swarm/Compose

### ISSUE THREAD

**Issue by till** [rzrbld/adminio-ui#23]
I can PR this if you let me know where, but otherwise, here is a "production" setup of the components which uses Traefik (v1.7) and avoids the entire cors thing. The following stack exposes the api component on a `/api` route via a `PathPrefix` with Traefik. And Traefik takes care of all the SSL, so there's nothing here.

If you remove the `deploy:` bit, this also works with Docker Compose.

Requirements:

 - traefik (v1.7) service running outside the stack
 - a network named `public` for traefik/ingress
 - a minio server running outside the stack

```yaml
version: '3.7'

networks:
  public:
    external: true
    name: public

services:
  adminio-api:
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:adminio-host.example.org; PathPrefix:/api"
        traefik.port: '8080'
    environment:
      ADMINIO_BACKENDS: '[{"name":"foo","url":"http://localhost:8080"}]'
      ADMINIO_HOST_PORT: 0.0.0.0:8080
      MINIO_ACCESS: access_key
      MINIO_HOST_PORT: minio_server:443
      MINIO_SECRET: secret
      MINIO_SSL: "true"
    image: rzrbld/adminio-api:release-1.6
    networks:
      public: {}
  adminio-ui:
    deploy:
      labels:
        traefik.docker.network: 'public'
        traefik.enable: "true"
        traefik.frontend.passHostHeader: 'true'
        traefik.frontend.rule: Host:adminio-host.example.org
        traefik.port: '80'
    environment:
      ADMINIO_MULTI_BACKEND: "false"
      ADMINIO_PROD: "true"
      API_BASE_URL: https://adminio-host.example.org
    image: rzrbld/adminio-ui:latest
    networks:
      public: {}
```
